//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Cache2003.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_CACHE2003_FORM              101
#define IDB_SPLASH                      103
#define IDC_CBFORMATO                   104
#define IDR_MAINFRAME                   128
#define IDR_CACHE2TYPE                  129
#define IDD_MEMORIAS_DLG                130
#define IDD_DIRECCION_DLG               135
#define IDD_POLITICAS_DLG               136
#define IDI_ETIQUETAS                   138
#define IDI_LINEAS                      139
#define IDI_PALABRAS                    140
#define IDI_CONJUNTOS                   141
#define IDI_ICON1                       143
#define IDD_CONTADOR_LINEAS             149
#define IDD_ESCRITURA_DLG               153
#define IDD_TIEMPOS                     154
#define IDD_ESTADISTICAS_DLG            156
#define IDD_DATOS_DLG                   158
#define IDD_DLG_BUSCAR                  159
#define IDD_SIMULACION_DLG              160
#define IDD_COLORES_DLG                 165
#define IDI_SIMULAR                     167
#define IDI_ULTIMO_DAT                  168
#define IDI_ANTERIOR_DAT                169
#define IDI_SIGUIENTE_DAT               170
#define IDI_PRIMERO_DAT                 171
#define IDI_ULTIMO_SEC                  172
#define IDI_ANTERIOR_SEC                173
#define IDI_SIGUIENTE_SEC               174
#define IDI_PRIMERO_SEC                 175
#define IDI_TIEMPOS                     176
#define IDI_SIMBOLOGIA                  177
#define IDI_ESTADISTICAS                178
#define IDI_OPCIONES                    179
#define IDI_ESCRITURA                   180
#define IDI_MEMORIAS                    181
#define IDI_POLITICAS                   182
#define IDI_BUSCAR                      183
#define IDI_DIRECCION                   184
#define IDI_AGREGAR                     185
#define IDI_EDITAR                      186
#define IDR_TOOLBAR_CONFIGURACION       187
#define IDR_TOOLBAR_DATOS               189
#define IDR_TOOLBAR_SECUENCIAS          191
#define IDC_N_MP                        1001
#define IDC_BYTES_MP                    1002
#define IDC_KBYTES_MP                   1003
#define IDC_MBYTES_MP                   1004
#define IDC_N_MC                        1005
#define IDC_BYTES_MC                    1006
#define IDC_KBYTES_MC                   1007
#define IDC_MBYTES_MC                   1008
#define IDC_N_BLOQUE                    1009
#define IDC_BYTES_BLOQUE                1010
#define IDC_KBYTES_BLOQUE               1011
#define IDC_MBYTES_BLOQUE               1013
#define IDC_INCRE_MP                    1015
#define IDC_DECRE_MP                    1016
#define IDC_INCRE_MC                    1017
#define IDC_DECRE_MC                    1018
#define IDC_INCRE_BLOQUE                1019
#define IDC_DECRE_BLOQUE                1020
#define IDC_STATIC_BYTESMP              1021
#define IDC_STATIC_KBYTES_MP            1022
#define IDC_STATIC_MBYTES_MP            1023
#define IDC_STATIC_BYTES_MC             1024
#define IDC_STATIC_KBYTES_MC            1025
#define IDC_STATIC_MBYTES_MC            1026
#define IDC_STATIC_BYTES_BLOQUE         1027
#define IDC_STATIC_KBYTES_BLOQUE        1028
#define IDC_STATIC_MBYTES_BLOQUE        1029
#define IDC_N_BITS1                     1031
#define IDC_N_BITS2                     1032
#define IDC_EDIT_CONJ                   1032
#define IDC_N_BITS3                     1033
#define IDC_N_BITS4                     1034
#define IDC_N_BITS5                     1035
#define IDC_N_BITS6                     1036
#define IDC_N_BITS7                     1037
#define IDC_POLIT_DIRECTO               1063
#define IDC_POLIT_ASOCIATIVO            1064
#define IDC_POLIT_A_COJUNTOS            1065
#define IDC_POLIT_ALEATORIO             1067
#define IDC_POLIT_LRU                   1068
#define IDC_POLIT_LFU                   1069
#define IDC_POLIT_FIFO                  1070
#define IDC_N_VIAS                      1071
#define IDC_D_ETIQUETA                  1072
#define IDC_D_LINEA                     1073
#define IDC_D_PALABRA                   1074
#define IDC_D_CONJUNTO                  1075
#define IDC_D_TOTAL_BITS                1076
#define IDC_BUTTON1                     1078
#define IDC_EDIT1                       1080
#define IDC_N_FILAS_MP                  1080
#define IDC_EDIT_N_MP                   1080
#define IDC_EDIT_DIR                    1080
#define IDC_EDIT_N_SEC                  1080
#define IDC_EDIT_TA_MP                  1080
#define IDC_EDIT_TASA_FALLOS            1080
#define IDC_EDIT_OCRE                   1080
#define IDC_REJILLA_MP                  1081
#define IDC_BTN_EJECUTAR                1082
#define IDC_BTN_LLENAR_MP               1082
#define IDC_REJILLA_MC                  1084
#define IDC_N_FILAS_MC                  1085
#define IDC_N_FILAS_BLOQUE              1087
#define IDC_P_EMPLAZAMIENTO             1091
#define IDC_P_REMPLAZAMIENTO            1092
#define IDC_SIMULAR                     1093
#define IDC_STATIC_DATO                 1094
#define IDC_EDIT_DATO                   1095
#define IDC_STATIC_PALABRA              1097
#define IDC_EDIT_PALABRA                1098
#define IDC_STATIC_BLOQUE               1099
#define IDC_EDIT_BLOQUE                 1100
#define IDC_STATIC_PALABRA_BLOQUE       1101
#define IDC_EDIT_PALABRA_BLOQUE         1102
#define IDC_STATIC_LINEA                1103
#define IDC_EDIT_LINEA                  1104
#define IDC_STATIC_N_LINEAS             1105
#define IDC_STATIC_N_BLOQUES_CONJ       1105
#define IDC_EDIT_N_BLOQUES_CONJ         1106
#define IDC_STATIC_N_CONJ               1108
#define IDC_EDIT_PALABRAS_CONJ          1109
#define IDC_EDIT_N_CONJ                 1111
#define IDC_STATIC_PALABRAS_CONJ        1112
#define IDC_STATIC_ACIERTOS             1113
#define IDC_EDIT_ACIERTOS               1114
#define IDC_EDIT_FALLOS                 1115
#define IDC_EDIT_SIMULACIONES           1116
#define IDC_STATIC_SIMULACIONES         1117
#define IDC_STATIC_FILAS                1118
#define IDC_STATIC_MP                   1119
#define IDC_STATIC_MC                   1120
#define IDC_STATIC_BLQ                  1121
#define IDC_STATIC_N_BLOQUES            1122
#define IDC_STATIC_MP2                  1123
#define IDC_STATIC_MC2                  1124
#define IDC_EDIT_BLOQUES_MP             1125
#define IDC_EDIT_BLOQUES_MC             1126
#define IDC_EDIT_W                      1127
#define IDC_EDIT_INI_LINEA              1128
#define IDC_EDIT_COLOR_VERDE            1129
#define IDC_EDIT_COLOR_ROJO             1130
#define IDC_CHECK_L_E                   1133
#define IDC_CHECK_CONT                  1134
#define IDC_STATIC_CONJ_MC              1135
#define IDC_STATIC_LINEA_CONJ           1137
#define IDC_EDIT_N_LINEAS               1139
#define IDC_CHECK_EDAD                  1140
#define IDC_CHECK_FREC                  1141
#define IDC_ESC_DIRECTA                 1152
#define IDC_ESC_POST                    1153
#define IDC_CON_ASIGNACION              1154
#define IDC_SIN_ASIGNACION              1155
#define IDC_EDIT_MET_EMPLAZA            1156
#define IDC_EDIT_MET_REEMPLAZA          1157
#define IDC_EDIT_TIP_ESC                1158
#define IDC_EDIT_ASIGNACION             1159
#define IDC_STATIC_DAT_MC               1161
#define IDC_STATIC_DATO_MP              1162
#define IDC_EDIT_DATO_MC                1166
#define IDC_STATIC_DATO_MC              1167
#define IDC_EDIT_TIPO_DATO              1168
#define IDC_EDIT_TIPO                   1169
#define IDC_STATIC_DATO_ESC             1170
#define IDC_EDIT_DATO_ESC               1171
#define IDC_STATIC_TIPO                 1173
#define IDC_EDIT_N_MC                   1174
#define IDC_EDIT_N_BLOQUE               1175
#define IDC_EDIT_N_VIAS                 1176
#define IDC_EDIT_DIRECCION              1177
#define IDC_STATIC_REEMPLAZA            1178
#define IDC_STATIC_EMPLAZA              1179
#define IDC_EDIT_DIRECCION2             1180
#define IDC_BUTTON2                     1181
#define IDC_BUTTON3                     1182
#define IDC_STATIC_D_ETIQUETA           1183
#define IDC_STATIC_D_LINEA              1184
#define IDC_STATIC_D_PALABRA            1185
#define IDC_STATIC_D_CONJUNTO           1186
#define IDC_MSCHART                     1187
#define IDC_STATIC_DIRECCION            1189
#define IDC_RADIO_LECTURA               1191
#define IDC_RADIO2                      1192
#define IDC_RADIO_ESCRITURA             1192
#define IDC_RADIO_MANUAL                1192
#define IDC_RADIO_SECUENCIAL            1192
#define IDC_B_AGREGAR                   1193
#define IDC_B_ELIMINAR                  1194
#define IDC_B_BUSCAR                    1195
#define IDC_STATIC_REGISTRO             1196
#define IDC_B_PRIMERO                   1197
#define IDC_B_ANTERIOR                  1198
#define IDC_B_SIGUIENTE                 1199
#define IDC_B_ULTIMO                    1200
#define IDC_DATOSDLG_DIRECCION          1201
#define IDC_DATOSDLG_DAT                1202
#define IDC_DATOSDLG_TIP                1204
#define IDC_STATIC_POSICION             1205
#define IDC_STATIC_DIR                  1208
#define IDC_STATIC_DAT                  1209
#define IDC_EDIT_REG                    1211
#define IDC_RADIO_LECT                  1213
#define IDC_RADIO_ESC                   1214
#define IDC_B_EDITAR                    1215
#define IDC_STATIC_SECUENCIA            1216
#define IDC_EDIT_SECUENCIA              1217
#define IDC_STATIC_DIR_SEC              1218
#define IDC_EDIT_DIR_SEC                1219
#define IDC_STATIC_REG_SEC              1220
#define IDC_B_PRIMERO_SEC               1221
#define IDC_B_ANTERIOR_SEC              1222
#define IDC_B_SIGUIENTE_SEC             1223
#define IDC_B_ULTIMO_SEC                1224
#define IDC_B_AGREGAR_SEC               1225
#define IDC_B_EDITAR_SEC                1226
#define IDC_EDIT_SEC                    1228
#define IDC_STATIC_FALLOS               1229
#define IDC_RADIO_AUTOMATICO            1230
#define IDC_RADIO_SEC_AUTOMATICA        1231
#define IDC_RADIO_MANUAL_SEC            1232
#define IDC_STATIC_N_SEC                1233
#define IDC_EDIT_AUTOMATICO             1234
#define IDC_EDIT_AUTOMATICO_SEC         1235
#define IDC_N_SECUENCIAS                1236
#define IDC_EDIT_TA_MC                  1237
#define IDC_RADIO_PARALELO              1238
#define IDC_RADIO_BASICA                1239
#define IDC_RADIO_NO_BASICA             1240
#define IDC_EDIT_T_PARALELO             1241
#define IDC_EDIT_T_BASICO               1242
#define IDC_EDIT_T_TP                   1243
#define IDC_EDIT_T_TC                   1244
#define IDC_EDIT_TA                     1245
#define IDC_EDIT_N_ESCRITURAS           1246
#define IDC_EDIT_TASA_ACIERTOS          1247
#define IDC_EDIT_POR_LECTURA            1248
#define IDC_EDIT_POR_ESCRITURA          1249
#define IDC_EDIT_TASA_PENALIZACION      1250
#define IDC_EDIT_PROB_MOD               1251
#define IDC_EDIT_TMA                    1252
#define IDC_EDIT_N_ESC                  1257
#define IDC_EDIT_TIPO_ESC               1259
#define IDC_EDIT_N_BLOQUES_MP           1260
#define IDC_EDIT_TACCESO                1261
#define IDC_B_DETALLES                  1262
#define IDC_STATIC_INFORME              1263
#define IDC_STATIC_TASAS                1264
#define IDC_STATIC_TOTAL                1265
#define IDC_STATIC_TASA_FALLOS          1266
#define IDC_STATIC_TASA_ACIERTOS        1267
#define IDC_STATIC_TASA_PENALIZA        1268
#define IDC_STATIC_LECT                 1269
#define IDC_STATIC_ESC                  1270
#define IDC_STATIC_PROB_MOD             1271
#define IDC_STATIC_TACCESO_MEDIO        1272
#define IDC_STATIC_TACCESO              1273
#define IDC_EDIT_TAM_MP                 1274
#define IDC_EDIT_T_ACIERTO              1275
#define IDC_STATIC_TACIERTO             1276
#define IDC_STATIC_TIEMPOS              1277
#define IDC_STATIC_PORCENTAJES          1278
#define IDC_STATIC_NS                   1279
#define IDC_STATIC_TA                   1280
#define IDC_STATIC_N_CONJUNTOS          1281
#define IDC_STATIC_DATOS_SIMULACION     1282
#define IDC_STATIC_UBICACIONES          1283
#define IDC_STATIC_EDICION              1284
#define IDC_STATIC_SECUENCIAS           1285
#define IDC_MP                          1286
#define IDC_MC                          1287
#define IDC_EDIT_COLOR_OCRE             1288
#define IDC_EDIT_COLOR_MOSTAZA          1289
#define IDC_EDIT_COLOR_ROSADO           1290
#define IDC_EDIT_COLOR_NARANJA          1291
#define IDC_EDIT_NARANJA                1294
#define IDC_EDIT_MOSTAZA                1295
#define IDC_EDIT_ROSADO                 1296
#define IDC_EDIT_AMARILLO               1297
#define IDC_EDIT_AZUL                   1298
#define IDC_EDIT_ROJO                   1299
#define IDC_EDIT_VERDE                  1300
#define IDC_EDIT_BLANCO                 1301
#define IDC_EDIT_GRIS                   1302
#define IDC_STATIC_TRANSFERENCIA        1310
#define IDC_STATIC_ACCESO               1311
#define IDC_STATIC_CICLO                1312
#define IDC_STATIC_POLITICAS            1313
#define IDC_STATIC_SEC                  1314
#define IDC_EDIT_CELESTE                1315
#define IDC_EDIT_ROJO2                  1316
#define IDC_STATIC_CELESTE              1317
#define IDC_STATIC_ROJO2                1318
#define IDC_STATIC_TEXTOS               1319
#define IDC_BUTTON                      1321
#define IDC_STATIC_MEAP                 1322
#define IDC_STATIC_CHCH                 1323
#define IDC_STATIC_TITULO               1324
#define IDC_STATIC_VERSION              1325
#define IDC_STATIC_COPY                 1326
#define IDC_STATIC_NMEAP                1327
#define IDC_STATIC_NCHCH                1328
#define IDC_STATIC_NTONINO              1329
#define IDC_STATIC_NCHCH2               1330
#define IDC_STATIC_NLADILLA             1331
#define ID_CONFIGURACION_MEMORIAS       32771
#define ID_CONFIGURAR_POLTICASDEEMPLAZAMIENTOYREEMPLAZAMIENTO 32772
#define ID_CONFIGURAR_POLTICAS          32772
#define ID_CONFIGURAR_POLTICASDEACTUALIZACIN 32773
#define ID_CONFIGURAR_ACTUALIZA         32773
#define ID_CONFIGURAR_FORMATODEINSTRUCCIONES 32774
#define ID_CONFIGURAR_FORMATO           32774
#define ID_CONFIGURAR_LLENADODEMEMORIAPRINCIPAL 32775
#define ID_CONFIGURAR_LLENADO_MP        32775
#define ID_EJECUTAR_OPCIONES            32776
#define ID_INSERTAR_DATOS_MP            32776
#define ID_EJECUTAR_TODOSLOSDATOSALAVEZ 32777
#define ID_VER_INFORMEDESIMULACIN       32778
#define ID_VER_DIRECCINDEMEMORIA        32779
#define ID_FORMAT_BINARIO               32780
#define ID_FORMAT_DECIMAL               32781
#define ID_FORMAT_HEXADECIMAL           32782
#define ID_FORMAT_OCTAL                 32783
#define ID_CONFIGURAR_TIEMPOSACCESO     32784
#define IDD_TIPO_DATO_MP                32785
#define IDD_TIPO_DATO_MC                32786
#define ID_CONFIGURACION_SIMULACION     32787
#define ID_FILE_PRINT_SEC               32788
#define ID_SIMBOLOGIA                   32789
#define ID_VIEW_CONFIGURACION_BAR       32814
#define ID_VIEW_DATOS_BAR               32815
#define ID_VIEW_SECUENCIAS_BAR          32816
#define ID_HELP_CACHE2003               32817
#define IDS_BINARIO                     61446
#define IDS_OCTAL                       61447
#define IDS_DECIMAL                     61448
#define IDS_HEXADECIMAL                 61449
#define ID_INDICADOR_ESC                61450
#define ID_INDICADOR_TIPO_ESC           61451

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1332
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
